-- DROP DATABASE
DROP DATABASE IF EXISTS user_db;

-- CREATE DATABASE
CREATE DATABASE user_db;

-- Users table
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

